Implement MiR Fleet Adapter
osrf/fleet_adapter_mir pull request #1
Opened 2020-08-27 09:38 UTC by methylDragon

Implements MiR fleet adapter using the RMF Fleet Adapter Python bindings

2020-09-09 03:31 UTC, mxgrey requested changes
I think this implementation is conceptually really great, and I'm very grateful for the amount of thought that went into it.

I do have some concerns about the complexity of the state management. Of course I understand that this complexity was necessary in order to interface correctly with the fleet adapter API, but my concern is that we don't have a very good way of testing this complexity without interfacing with a real MiR server.

I think in the long run, we'll want to refactor migrate this work into the ongoing free fleet effort. That way we can isolate the state management logic from the MiR API and do proper unit testing. Then I'll feel much more comfortable with the level of complexity here.

I've left some comments for things that look like they could be errors. Some of those comments might be incorrect, since I might just be misunderstanding some details of the implementation.

2020-09-11 07:07 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +            self.rmf_remaining_path.append(_msg)
Whoops! I mixed up another class variable. I'm supposed to be populating an array of Locations to feed into the RobotState message for publishing the FleetState in a downstream script (e.g. in `main.py`)

Also, a note on the robot state message path member. In ROS1 I noticed that paths are in [last, ..., first] order. Is that the same for RMF? (Notably, the RMF plan waypoints are given in [first, ..., last] order)

Updated: 5f6bd6e37cd3c7f403671bd4c4e7ed643932da1b

2020-09-11 07:08 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +            self.rmf_current_lane_index = 0
Updated: 44660a25edde4127f610b6d64508b2836805fd4e

2020-09-11 07:18 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +        elif self.rmf_target_waypoint_index:  # In Unknown Lane
Updated: dad547bb9bc3b84b366f3b70e4b81e04243704b9

2020-09-11 07:18 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +        elif self.rmf_current_lane_index:
Updated: dad547bb9bc3b84b366f3b70e4b81e04243704b9

2020-09-11 07:18 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +        if self.rmf_current_waypoint_index:
Updated: dad547bb9bc3b84b366f3b70e4b81e04243704b9

2020-09-11 17:32 UTC, methylDragon commented on main.py
> +def create_nav_graph(config):
Good point, updated: cd2cd394cbbace544e5cfbe073c1aa002a2f9967

2020-09-11 17:51 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +                    self.stop()
I don't understand :O

This section is explicitly for pre-empting/killing the thread (when the quit event flag is set). So new path_closure threads are supposed to be spun up before this call to stop can happen.

Before any new threads are spun up, old threads are killed by a call to [`self.stop()`](https://github.com/osrf/fleet_adapter_mir/pull/1/files/7dcb4d5d46ce188e8fa1f28814ceb50f3798daef#diff-1d43fe5e5105e78b185ef39c7d4868f4R209)

```
    def follow_new_path(self,
                        waypoints,
                        next_arrival_estimator,  # function!
                        path_finished_callback):
        self.stop()  # <--- here
        self.current_task_id += 1
```

And `self.stop()` blocks until threads are killed. (Due to the `join()` call.)

I am hesitant to

2020-09-11 18:02 UTC, methylDragon commented on fleet_adapter_mir/fleet_adapter_mir.py
> +                    self.stop()
Oh, actually I see the issue.

Hopefully this wait fixes it? 8b8dd79467253e3e6e977ee9c653ea72266230bd

2020-12-08 08:25 UTC, merged

2020-12-08 08:25 UTC, mxgrey commented
To move this review along, I'm going to merge it into a branch of this repo and open a new PR into main so I can push changes directly.