Perform action
osrf/fleet_adapter_mir pull request #15
Opened 2022-08-30 18:45 UTC by aaronchongth

2022-09-06 16:00 UTC, mxgrey requested changes
I left a few comments about things that I think should be changed, but also some suggestions that are just meant to be notes for potential future improvements.

2022-09-07 10:12 UTC, aaronchongth commented on configs/mir_config.yaml
> +    action_categories: ["dock_to_charger", "custom_mission_1"]
Yup that definitely sounds like a much better way to handle `perform_action`, thanks! I've created the issue, https://github.com/osrf/fleet_adapter_mir/issues/19

2022-09-07 10:12 UTC, aaronchongth commented on fleet_adapter_mir/MiRCommandHandle.py
> +            self.node.get_logger().warn(f"Robot [{self.name}] starts [{category}] action")
https://github.com/osrf/fleet_adapter_mir/pull/15/commits/1e412a7f292e350aaeeaa607c1cba44bedef4521

2022-09-07 10:12 UTC, aaronchongth commented on fleet_adapter_mir/MiRCommandHandle.py
> +                self.node.get_logger().error(f'Action category {category} not supported, ignoring')
https://github.com/osrf/fleet_adapter_mir/pull/15/commits/6dcefd53abaa53d440b0d0637816449ad4ae24a7

2022-09-07 10:12 UTC, aaronchongth commented on fleet_adapter_mir/MiRCommandHandle.py
> +            self.action_check_task_completion
https://github.com/osrf/fleet_adapter_mir/pull/15/commits/24707585d1560293d96b8084df7798c579f20daf

2022-09-07 10:13 UTC, aaronchongth commented on fleet_adapter_mir/MiRCommandHandle.py
> +            self.action_execution = execution
Thanks for the suggestion, it is definitely much cleaner now.
https://github.com/osrf/fleet_adapter_mir/pull/15/commits/80e30203af3b7961012c7cce033f28a2a29d8c78

2022-11-21 04:25 UTC, mxgrey approved these changes
Thanks for the changes!

2022-11-21 05:06 UTC, merged